Blood-Bank-Management-System-master/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

Blood-Bank-Management-System-master/polls/urls.py
from django.urls import path
from .views import home, about, donor_registration, search, search_info, contact


urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('donor_registration/', donor_registration,
         name='donor_registration'),
    path('donor_registration/donor_list/',
         donor_registration, name='donor_list'),
    path('search/', search, name='search'),
    path('search_list/', search, name='search_list'),
    path('search/search_list/search_info/<email>/',
         search_info, name='search_info'),
    path('contact/', contact, name='contact'),
]

Blood-Bank-Management-System-master/polls/models.py
from django.db import models


class donor_Registration(models.Model):

    name = models.CharField(
        max_length=50,
        blank=True,
        null=True,
    )

    father_name = models.CharField(
        max_length=50,
        blank=True,
        null=True,
    )

    gender_choices = [
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Other')
    ]
    gender = models.CharField(
        max_length=6,
        blank=True,
        null=True,
        choices=gender_choices,
    )

    email = models.EmailField(
        max_length=50,
        blank=True,
        null=True
    )

    phone_number = models.IntegerField(
        blank=True,
        null=True,
    )

    state = models.CharField(
        max_length=50,
        blank=True,
        null=True,
    )

    city = models.CharField(
        max_length=50,
        blank=True,
        null=True,
    )

    date_of_birth = models.DateField(
        blank=True,
        null=True,
    )

    occupation = models.CharField(
        max_length=15,
        blank=True,
        null=True,
    )

    blood_group_choices = [
        ('a+', 'A+'),
        ('a-', 'A-'),
        ('b+', 'B+'),
        ('b', 'B'),
        ('b-', 'B-'),
        ('o+', 'O+'),
        ('ab+', 'AB+'),
        ('ab-', 'AB-'),
    ]

    blood_group = models.CharField(
        max_length=4,
        blank=True,
        null=True,
        choices=blood_group_choices,
    )

    home_address = models.TextField(
        max_length=500,
        blank=True,
        null=True,
    )

    last_donate_date = models.DateField(
        blank=True,
        null=True,
    )

    any_diseases_choices = [
        ('yes', 'Yes'),
        ('no', 'No'),
    ]

    any_disease = models.CharField(
        max_length=4,
        blank=True,
        null=True,
        choices=any_diseases_choices,
    )

    allergies_choices = [
        ('yes', 'Yes'),
        ('no', 'No'),
    ]

    allergies = models.CharField(
        max_length=4,
        blank=True,
        null=True,
        choices=allergies_choices,
    )

    cardiac_choices = [
        ('yes', 'Yes'),
        ('no', 'No'),
    ]

    cardiac = models.CharField(
        max_length=4,
        blank=True,
        null=True,
        choices=cardiac_choices,
    )

    bleeding_disorder_choices = [
        ('yes', 'Yes'),
        ('no', 'No'),
    ]

    bleeding_disorder = models.CharField(
        max_length=4,
        blank=True,
        null=True,
        choices=bleeding_disorder_choices,
    )

    hbsAg_hcv_hIV_choices = [
        ('yes', 'Yes'),
        ('no', 'No'),
    ]

    hbsAg_hcv_hIV = models.CharField(
        max_length=4,
        blank=True,
        null=True,
        choices=hbsAg_hcv_hIV_choices,
    )

    def __str__(self):
        return self.name


class sea_rch(models.Model):

    blood_group_choices = [
        ('a+', 'A+'),
        ('a-', 'A-'),
        ('b+', 'B+'),
        ('b', 'B'),
        ('b-', 'B-'),
        ('o+', 'O+'),
        ('ab+', 'AB+'),
        ('ab-', 'AB-'),
    ]

    blood_group = models.CharField(
        max_length=4,
        blank=True,
        null=True,
        choices=blood_group_choices,
    )

    state = models.CharField(
        max_length=50,
        blank=True,
        null=True,
    )

    city = models.CharField(
        max_length=50,
        blank=True,
        null=True,
    )


class con_tact(models.Model):

    name = models.CharField(
        max_length=50,
        blank=True,
        null=True,
    )

    phone_number = models.IntegerField(
        blank=True,
        null=True,
    )

    email = models.EmailField(
        max_length=50,
        blank=True,
        null=True
    )

    subject = models.TextField(
        max_length=500,
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.name

Blood-Bank-Management-System-master/polls/forms.py
from django import forms
from django.forms import ModelForm
from . import models


class DonorRegistration(ModelForm):
    class Meta:
        model = models.donor_Registration
        fields = '__all__'
        widgets = {'name': forms.TextInput(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Enter Your Name'}),
            'father_name': forms.TextInput(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Enter Your Father Name'}),
            'gender': forms.Select(
            attrs={'class': 'form-control', 'required': 'True'}),
            'email': forms.EmailInput(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Enter Your E-mail'}),
            'phone_number': forms.NumberInput(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Enter Your Phone Number'}),
            'state': forms.TextInput(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Enter Your State'}),
            'city': forms.TextInput(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Enter Your City'}),
            'date_of_birth': forms.DateInput(
            attrs={'class': 'form-control', 'required': 'True', 'type': 'date', 'placeholder': 'Enter Your D.O.B.'}),
            'occupation': forms.TextInput(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Enter Your Occupation'}),
            'blood_group': forms.Select(
            attrs={'class': 'form-control', 'required': 'True'}),
            'home_address': forms.Textarea(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Enter Your Home Address'}),
            'last_donate_date': forms.DateInput(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Enter Your Last Donate Date'}),
            'any_disease': forms.Select(
            attrs={'class': 'form-control', 'required': 'True'}),
            'allergies': forms.Select(
            attrs={'class': 'form-control', 'required': 'True'}),
            'cardiac': forms.Select(
            attrs={'class': 'form-control', 'required': 'True'}),
            'bleeding_disorder': forms.Select(
            attrs={'class': 'form-control', 'required': 'True'}),
            'hbsAg_hcv_hIV': forms.Select(
            attrs={'class': 'form-control', 'required': 'True'}),

        }



class Search(forms.ModelForm):
    class Meta:
        model = models.sea_rch
        fields = '__all__'
        widgets = {'blood_group': forms.Select(
            attrs={'class': 'form-control', 'required': 'True'}),
            'state': forms.TextInput(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Enter Your State'}),
            'city': forms.TextInput(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Enter Your City'}),
        }


class Contact(forms.ModelForm):
    class Meta:
        model = models.con_tact
        fields = '__all__'
        widgets = {'name': forms.TextInput(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Name'}),
            'phone_number': forms.NumberInput(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Phone Number'}),
            'email': forms.EmailInput(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'E-mail'}),
            'subject': forms.Textarea(
            attrs={'class': 'form-control', 'required': 'True', 'placeholder': 'Subject...'}),
        }

Blood-Bank-Management-System-master/polls/views.py
from django.shortcuts import render
from .forms import DonorRegistration, Contact, Search
from .models import donor_Registration, sea_rch, con_tact


def home(request):
    return render(request, 'polls/base.html')


def about(request):
    return render(request, 'polls/about.html')


def donor_registration(request):
    forms = DonorRegistration()
    if request.method == 'POST':
        forms = DonorRegistration(request.POST)
        if forms.is_valid():
            forms.save()
            context = {
                'forms': forms
            }

            return render(request, 'polls/donor_list.html', context)

        print(forms.errors)

    context_form = {
        'forms': forms
    }

    return render(request, 'polls/donor_registration.html', context_form)


def search(request):
    forms = Search()
    if request.method == 'POST':
        forms = Search(request.POST)
        if forms.is_valid():
            forms.save()
            bloodgroup = forms.cleaned_data['blood_group']
            state = forms.cleaned_data['state']
            city = forms.cleaned_data['city']
            donor_filter = donor_Registration.objects.filter(blood_group=bloodgroup,
                                                             state=state,
                                                             city=city,
                                                             )
            context = {
                'donor_filter': donor_filter
            }

            return render(request, 'polls/search_list.html', context)

        print(forms.errors)

    context_form = {
        'forms': forms
    }

    return render(request, 'polls/search.html', context_form)


def search_info(request, email):
    email = email
    detail = donor_Registration.objects.get(email=email)

    context = {
        'details': detail
    }

    return render(request, 'polls/search_info.html', context)


def contact(request):
    forms = Contact()
    if request.method == 'POST':
        forms = Contact(request.POST)
        if forms.is_valid():
            forms.save()

    context = {
        'forms': forms
    }

    return render(request, 'polls/contact.html', context)

Blood-Bank-Management-System-master/templates/polls/about.html
{% extends 'polls/base.html' %} {% block title %}<title>About</title>
{% endblock%} {% block contents %}

<style>
  h2 {
    color: #d9534f;
  }

  .width-border {
    border-radius: 12px;
    width: 100%;
    border: 1px solid #d9534f;
  }
</style>

<div class="container">
  <div class="p-5">
    <div class="shadow-lg p-5 mb-3 bg-white width width-border mx-auto">
      <div class="font">
        <h2 class="text-center font-weight-bold">Benefits</h2>
        <hr />
        <p>
          Donating blood has benefits for your emotional and physical health.
          According to a report by the Mental Health Foundation, helping others
          can:
        </p>
        <ul>
          <li>reduce stress</li>
          <li>improve your emotional well-being</li>
          <li>benefit your physical health</li>
          <li>help get rid of negative feelings</li>
          <li>provide a sense of belonging and reduce isolation</li>
        </ul>
        <p>
          Research has found further evidence of the health benefits that come
          specifically from donating blood.
        </p>

        <h2 class="text-center font-weight-bold">Free health checkup</h2>
        <hr />
        <p>
          In order to give blood, you’re required to undergo a health screening.
          A trained staff member performs this checkup. They’ll check your:
        </p>
        <ul>
          <li>pulse</li>
          <li>blood pressure</li>
          <li>body temperature</li>
          <li>hemoglobin levels</li>
        </ul>
        <p>
          This free mini-physical can offer excellent insight into your health.
          It can effectively detect problems that could indicate an underlying
          medical condition or risk factors for certain diseases.
        </p>

        <p>Your blood is also tested for several diseases. These include:</p>
        <ul>
          <li>hepatitis B</li>
          <li>hepatitis C</li>
          <li>HIV</li>
          <li>West Nile virus</li>
          <li>syphilis</li>
          <li>Trypanosoma cruzi</li>
        </ul>
        <h2 class="text-center font-weight-bold">
          Side effects of donating blood
        </h2>
        <hr />
        <p>
          Blood donation is safe for healthy adults. There’s no risk of
          contracting disease. New, sterile equipment is used for each donor.
          <br /><br />
          Some people may feel nauseous, lightheaded, or dizzy after donating
          blood. If this happens, it should only last a few minutes. You can lie
          down with your feet up at the until you feel better.
          <br /><br />
          You may also experience some bleeding at the site of the needle.
          Applying pressure and raising your arm for a couple of minutes will
          usually stop this. You may develop a bruise at the site.
          <br />
          Call the blood donation center if:
        </p>
        <ul>
          <li>
            You still feel lightheaded, dizzy, or nauseous after drinking,
            eating, and resting.
          </li>
          <li>
            You develop a raised bump or continue bleeding at the needle site.
          </li>
          <li>You have arm pain, numbness, or tingling.</li>
        </ul>
        <h2 class="text-center font-weight-bold">During the donation</h2>
        <hr />
        <p>
          You must register to donate blood. This includes providing
          identification, your medical history, and undergoing a quick physical
          examination. You’ll also be given some information about blood
          donation to read. <br /><br />
          Once you’re ready, your blood donation procedure will begin. Whole
          blood donation is the most common type of donation. This is because it
          offers the most flexibility. It can be transfused as whole blood or
          separated into red cells, platelets, and plasma for different
          recipients.
          <br /><br />
          For a whole blood donation procedure:
        </p>
        <ol>
          <li>
            You’ll be seated in a reclining chair. You can donate blood either
            sitting or lying down.
          </li>
          <li>
            A small area of your arm will be cleaned. A sterile needle will then
            be inserted.
          </li>
          <li>
            You’ll remain seated or lying down while a pint of your blood is
            drawn. This takes 8 to 10 minutes.
          </li>
          <li>
            When a pint of blood has been collected, a staff member will remove
            the needle and bandage your arm.
          </li>
        </ol>
        <p>
          Other types of donation include:
          <br />
        </p>

        <ul>
          <li>platelet donation (plateletpheresis)</li>
          <li>plasma donation (plasmapheresis)</li>
          <li>double red cell donation</li>
        </ul>
        <p>
          These types of donations are performed using a process called
          apheresis. An apheresis machine is connected to both of your arms. It
          collects a small amount of blood and separates the components before
          returning the unused components back to you. This cycle is repeated
          several times over approximately two hours. <br /><br />
          Once your donation is complete, you’ll be given a snack and a drink
          and be able to sit and rest for 10 or 15 minutes before you leave. If
          you feel faint or nauseous, you’ll be able to lie down until you feel
          better.
        </p>

        <h2 class="text-center font-weight-bold">
          What to know before you donate
        </h2>
        <hr />
        <p>Here are some important things to know before you donate:</p>
        <ul>
          <li>
            You need to be 17 or older to donate whole blood. Some states allow
            you to donate at 16 with parental consent.
          </li>
          <li>
            You have to weigh at least 110 pounds and be in good health to
            donate.
          </li>
          <li>
            You need to provide information about medical conditions and any
            medications you’re taking. These may affect your eligibility to
            donate blood.
          </li>
          <li>
            You must wait at least 8 weeks between whole blood donations and 16
            weeks between double red cell donations.
          </li>
          <li>
            Platelet donations can be made every 7 days, up to 24 times per
            year.
          </li>
        </ul>
        <p>
          The following are some suggestions to help you prepare for donating
          blood:
        </p>
        <ul>
          <li>Drink an extra 16 ounces of water before your appointment.</li>
          <li>Eat a healthy meal that’s low in fat.</li>
          <li>
            Wear a short-sleeved shirt or a shirt with sleeves that are easy to
            roll up.
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

{% endblock %}

Blood-Bank-Management-System-master/templates/polls/base.html

{% load static %}
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link href="{% static 'css/all.min.css' %}" rel="stylesheet" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="{% static 'images/title.jpg' %}"
    />

    {% block title %}
    <title>Home</title>
    {% endblock %}
  </head>
  <style>
    .bg-danger:hover {
      background-color: white;
      color: #d9534f;
    }

    .nav :hover {
      color: white;
      background-color: #d9534f;
      border-radius: 6px;
    }

    .nav-link {
      color: #d9534f;
      border: 1.5px solid #d9534f;
      border-radius: 6px;
      margin-left: 8px;
    }

    .carousel-item {
      height: 71.8vh;
      min-height: 200px;
      background: no-repeat scroll center scroll;
      background-size: cover;
    }

    .carousel-item::before {
      content: "";
      display: block;
      position: absolute;
      top: 0;
      left: 0;
      bottom: 0;
      right: 0;
      background: #000;
      opacity: 0.5;
    }

    .carousel-caption {
      bottom: 100px;
      padding-left: 100px;
      padding-right: 100px;
    }

    .carousel-caption h5 {
      font-size: 50px;
      font-weight: 600;
    }

    .carousel-caption p {
      font-size: 25px;
      top: 2rem;
    }

    footer p {
      color: white;
    }

    footer p a {
      color: #fc7b19;
      text-decoration: none;
    }

    footer p a:hover {
      color: white;
    }
  </style>

  <body>
    <div class="container-fluid bg-danger">
      <div class="p-4">
        <div class="text-center text-white fs-2">Blood Management System</div>
      </div>
    </div>
    <div class="container-fluid border">
      <nav class="navbar bg-white">
        <a class="navbar-brand" href="#">
          <img
            src="{% static 'images/logo.png' %}"
            width="80"
            height="80"
            alt=""
          />
        </a>

        <ul class="nav justify-content-end">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'donor_registration' %}"
              >Donor Registration</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'search' %}">Search</a>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link"
              href="/admin/login/?next=/admin/"
              data-toggle="dropdown"
            >
              Admin
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
          </li>
        </ul>
      </nav>
    </div>
    {% block contents %}

    <div
      id="carouselExampleCaptions"
      class="carousel slide"
      data-bs-ride="carousel"
    >
      <div class="carousel-indicators">
        <button
          type="button"
          data-bs-target="#carouselExampleCaptions"
          data-bs-slide-to="0"
          class="active"
          aria-current="true"
          aria-label="Slide 1"
        ></button>
        <button
          type="button"
          data-bs-target="#carouselExampleCaptions"
          data-bs-slide-to="1"
          aria-label="Slide 2"
        ></button>
        <button
          type="button"
          data-bs-target="#carouselExampleCaptions"
          data-bs-slide-to="2"
          aria-label="Slide 3"
        ></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img
            src="{% static 'images/slide1.jpg' %}"
            class="d-block w-100 h-100"
            alt="..."
          />
          <div class="carousel-caption d-none d-md-block">
            <h5>Just Donate Blood</h5>
            <p>
              “Donate Blood Because You Never Know How Helpful It Might Be To
              Someone.”
            </p>
          </div>
        </div>
        <div class="carousel-item">
          <img
            src="{% static 'images/slide2.jpg' %}"
            class="d-block w-100 h-100"
            alt="..."
          />
          <div class="carousel-caption d-none d-md-block">
            <h5>Just Donate Blood</h5>
            <p>
              “Blood Donation Is A Small Act Of Kindness That Does Great And Big
              Wonders.”
            </p>
          </div>
        </div>
        <div class="carousel-item">
          <img
            src="{% static 'images/slide3.jpg' %}"
            class="d-block w-100 h-100"
            alt="..."
          />
          <div class="carousel-caption d-none d-md-block">
            <h5>Just Donate Blood</h5>
            <p>
              “Blood Donation Costs You Nothing, But It Can Mean The World To
              Someone In Need.”
            </p>
          </div>
        </div>
      </div>
      <button
        class="carousel-control-prev"
        type="button"
        data-bs-target="#carouselExampleCaptions"
        data-bs-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button
        class="carousel-control-next"
        type="button"
        data-bs-target="#carouselExampleCaptions"
        data-bs-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    {% endblock %}
    <footer class="p-2 text-center bg-danger">
      <p class="mt-3">
        Created By
        <a href="simranlotey.github.io">Chikatimalla SaiGanesh</a>
        | This Site is
        <a
          href="https://github.com/simranlotey/Blood-Bank-Management-System.git"
          target="_blank"
          >Open Source</a
        >
      </p>

      <p></p>
    </footer>

    <script src="{% static 'js/all.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

Blood-Bank-Management-System-master/templates/polls/contact.html



<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link href="/static/css/all.min.css" rel="stylesheet" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="/static/images/title.jpg"
    />

    <title>Contact</title>

  </head>
  <style>
    .bg-danger:hover {
      background-color: white;
      color: #d9534f;
    }

    .nav :hover {
      color: white;
      background-color: #d9534f;
      border-radius: 6px;
    }

    .nav-link {
      color: #d9534f;
      border: 1.5px solid #d9534f;
      border-radius: 6px;
      margin-left: 8px;
    }

    .carousel-item {
      height: 71.8vh;
      min-height: 200px;
      background: no-repeat scroll center scroll;
      background-size: cover;
    }

    .carousel-item::before {
      content: "";
      display: block;
      position: absolute;
      top: 0;
      left: 0;
      bottom: 0;
      right: 0;
      background: #000;
      opacity: 0.5;
    }

    .carousel-caption {
      bottom: 100px;
      padding-left: 100px;
      padding-right: 100px;
    }

    .carousel-caption h5 {
      font-size: 50px;
      font-weight: 600;
    }

    .carousel-caption p {
      font-size: 25px;
      top: 2rem;
    }

    footer p {
      color: white;
    }

    footer p a {
      color: #fc7b19;
      text-decoration: none;
    }

    footer p a:hover {
      color: white;
    }
  </style>

  <body>
    <div class="container-fluid bg-danger">
      <div class="p-4">
        <div class="text-center text-white fs-2">Blood Management System</div>
      </div>
    </div>
    <div class="container-fluid border">
      <nav class="navbar bg-white">
        <a class="navbar-brand" href="#">
          
        </a>

        <ul class="nav justify-content-end">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about/">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/donor_registration/"
              >Donor Registration</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/search/">Search</a>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link"
              href="/admin/login/?next=/admin/"
              data-toggle="dropdown"
            >
              Admin
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/contact/">Contact Us</a>
          </li>
        </ul>
      </nav>
    </div>
    
<style>
  .width-border {
    border-radius: 12px;
    border: 1px solid #d9534f;
    display: flex;
  }
  .containers {
    flex-direction: column;
    align-items: center;
    display: flex;
    justify-content: center;
  }
</style>

<div class="containers">
  <div class="p-5">
    <div class="shadow-lg w-75 p-5 mb-3 bg-white round width-border mx-auto">
      <form action="" method="post">
        <h2 class="text-center text-danger text-uppercase">Contact Us</h2>
        <br /><br />

        <div class="row">
          <div class="col-lg-6">
            <div class="p-3">
              <div class="row">
                <div class="col-2">
                  <i class="fas fa-user" style="font-size: 20px"></i>
                </div>
                <div class="col-10">
                  <p style="font-size: 17px">CH.Sai Ganesh</p>
                  <p style="font-size: 17px">CH.Sumanth</p>
                  <p style="font-size: 17px">G.Akshay</p>
                </div>
                <br /><br />
                <div class="col-2">
                  <i class="fas fa-phone" style="font-size: 20px"></i>
                </div>
                <div class="col-10">
                  <p style="font-size: 17px">+9193468XXXXX</p>
                </div>
                <br /><br />
                <div class="col-2">
                  <i class="fas fa-envelope" style="font-size: 20px"></i>
                </div>
                <div class="col-10">
                  <p style="font-size: 17px">cmrbloodbank@gmail.com</p>
                </div>
                <br /><br />
                <div class="col-2">
                  <i class="fas fa-map-marker-alt" style="font-size: 20px"></i>
                </div>
                <div class="col-10">
                  <p style="font-size: 17px">CMR HOSPITAL,Kandlakoya,Medchal</p>
                </div>
                <br /><br />
              </div>
            </div>
          </div>
          <div class="col-lg-6">
            <input type="hidden" name="csrfmiddlewaretoken" value="IW98YYElwfiq5olaMgyV9PPQwWSl3HFxuGs5J6Ch0NOdf7P4w0DIPrSuQDYgUPka"> <p><label for="id_name">Name:</label> <input type="text" name="name" class="form-control" required="True" placeholder="Name" maxlength="50" id="id_name"></p>
<p><label for="id_phone_number">Phone number:</label> <input type="number" name="phone_number" class="form-control" required="True" placeholder="Phone Number" id="id_phone_number"></p>
<p><label for="id_email">Email:</label> <input type="email" name="email" class="form-control" required="True" placeholder="E-mail" maxlength="50" id="id_email"></p>
<p><label for="id_subject">Subject:</label> <textarea name="subject" cols="40" rows="10" class="form-control" required="True" placeholder="Subject..." maxlength="500" id="id_subject">
</textarea></p>
            <button type="submit" class="btn btn-danger">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>


    <footer class="p-2 text-center bg-danger">
      <p class="mt-3">
        Created By
        <a href="simranlotey.github.io">Chikatimalla SaiGaneash</a>
        | This Site is
        <a
          href="https://github.com/simranlotey/Blood-Bank-Management-System.git"
          target="_blank"
          >Open Source</a
        >
      </p>

      <p></p>
    </footer>

    <script src="/static/js/all.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
  </body>
</html>